### ISSUE TITLE
Dependency on com.google.common.collect not properly incorporated

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#121]
The dependency on com.google.common.collect introduced to AbstractExecutionContext in fixing https://github.com/Protelis/Protelis/issues/110 is not properly incorporated into the release distribution. For 10.3.1, at least, the dependency chain is not resolved by Maven and we end up with errors of this form:

```
java.lang.NoSuchMethodError: com.google.common.collect.Maps.newLinkedHashMapWithExpectedSize(I)Ljava/util/LinkedHashMap;
	at org.protelis.vm.impl.AbstractExecutionContext.setup(AbstractExecutionContext.java:108)
	at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:43)
```

**Comment by jakebeal** [comment]
On further inspection, I think this may be some sort of version skew issue.  Maven is, in fact, pulling in guava-14.0.1, a library that contains com.google.common.collect.Maps, it's just that the newLinkedHashMapWithExpectedSize method doesn't appear to exist in that class. I've updated with "force updates" on, without successful resolution, so my guess is that the method appeared in some particular revision but that Protelis's dependency resolution isn't constraining enough.

**Comment by jakebeal** [comment]
Looks like this method wasn't introduced until guava-19.0.  I've updated the dependency, and will request a pull.

**Comment by DanySK** [comment]
Guava 14.0.1 is the latest JDK5 compatible version. I believe Xtext is JDK 5 compatible. This issue must be investigated by carefully checking the dependency produced by Gradle:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.google.code.findbugs:findbugs:[3.0.0, 3.0.1] -> 3.0.1
|    +--- net.jcip:jcip-annotations:1.0
|    +--- com.google.code.findbugs:jsr305:2.0.1
|    +--- com.google.code.findbugs:bcel-findbugs:6.0
|    +--- com.google.code.findbugs:jFormatString:2.0.1
|    +--- dom4j:dom4j:1.6.1
|    |    \--- xml-apis:xml-apis:1.0.b2
|    +--- org.ow2.asm:asm-debug-all:5.0.2
|    +--- org.ow2.asm:asm-commons:5.0.2
|    |    \--- org.ow2.asm:asm-tree:5.0.2
|    |         \--- org.ow2.asm:asm:5.0.2
|    +--- commons-lang:commons-lang:2.6
|    +--- com.apple:AppleJavaExtensions:1.4
|    \--- jaxen:jaxen:1.1.6
+--- org.apache.commons:commons-math3:[3.3, 3.6.1] -> 3.6.1
+--- org.slf4j:slf4j-api:[1.7.0, 1.8[ -> 1.7.25
+--- project :protelis-interpreter
|    +--- com.google.code.findbugs:findbugs:[3.0.0, 3.0.1] -> 3.0.1 (*)
|    +--- org.apache.commons:commons-math3:[3.3, 3.6.1] -> 3.6.1
|    +--- org.slf4j:slf4j-api:[1.7.0, 1.8[ -> 1.7.25
|    +--- commons-codec:commons-codec:[1.7, 2[ -> 1.10
|    +--- commons-io:commons-io:[2.3, 2.5] -> 2.5
|    +--- net.sf.trove4j:trove4j:[3.0.1, 4[ -> 3.0.3
|    +--- com.google.guava:guava:[11.0, 22[ -> 21.0
|    +--- org.apache.commons:commons-lang3:[3.2, 3.5] -> 3.5
|    +--- org.danilopianini:javalib-java7:[0.1.1, 1[ -> 0.6.1
|    |    +--- com.google.guava:guava:[11.0, 19.0-rc2] -> 21.0
|    |    +--- com.google.code.findbugs:findbugs:[3.0.0, 3.0.1] -> 3.0.1 (*)
|    |    +--- net.sf.trove4j:trove4j:[3.0.1, 4) -> 3.0.3
|    |    \--- commons-io:commons-io:[1, 3) -> 2.5
|    +--- org.danilopianini:javalib:[5.0.0, 6[ -> 5.0.0
|    |    +--- net.sourceforge.streamsupport:streamsupport:[1.4.2, 2) -> 1.5.4
|    |    +--- org.danilopianini:javalib-java7:[0.3.0, 2) -> 0.6.1 (*)
|    |    +--- org.apache.commons:commons-math3:[3, 4) -> 3.6.1
|    |    \--- com.google.guava:guava:[r03, 19.0] -> 21.0
|    +--- org.springframework:spring-core:[4.1.6.RELEASE, 4.3.4.RELEASE] -> 4.3.4.RELEASE
|    |    \--- commons-logging:commons-logging:1.2
|    +--- org.protelis:protelis.parser:[5.0.0, 6[ -> 5.0.0
|    |    +--- org.eclipse.xtext:org.eclipse.xtext:2.8.4
|    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.util:[2.8.4] -> 2.8.4
|    |    |    |    +--- com.google.guava:guava:[10.0.1,14.0.1] -> 21.0
|    |    |    |    +--- com.google.inject:guice:3.0
|    |    |    |    |    +--- javax.inject:javax.inject:1
|    |    |    |    |    +--- aopalliance:aopalliance:1.0
|    |    |    |    |    \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111
|    |    |    |    +--- log4j:log4j:1.2.15 -> 1.2.16
|    |    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:[2.9.0,) -> 2.12.0
|    |    |    |    \--- org.eclipse.emf:org.eclipse.emf.common:[2.9.0,) -> 2.12.0
|    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:[2.8.4] -> 2.8.4
|    |    |    |    \--- com.google.guava:guava:[10.0.1,14.0.1] -> 21.0
|    |    |    +--- com.google.guava:guava:[10.0.1,14.0.1] -> 21.0
|    |    |    +--- com.google.inject:guice:3.0 (*)
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:(2.8,3.0) -> 2.12.0
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.common:(2.8,3.0) -> 2.12.0
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore.xmi:(2.8,3.0) -> 2.12.0
|    |    |    +--- log4j:log4j:1.2.16
|    |    |    +--- com.ibm.icu:icu4j:52.1
|    |    |    \--- org.antlr:antlr-runtime:[3.2] -> 3.2
|    |    +--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.8.4
|    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.util:[2.8.4] -> 2.8.4 (*)
|    |    |    +--- org.eclipse.xtext:org.eclipse.xtext:[2.8.4] -> 2.8.4 (*)
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.codegen:(2.8,3.0) -> 2.11.0
|    |    |    +--- com.google.guava:guava:[10.0.1,14.0.1] -> 21.0
|    |    |    +--- com.google.inject:guice:3.0 (*)
|    |    |    +--- org.ow2.asm:asm-commons:5.0.1 -> 5.0.2 (*)
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:(2.8,3.0) -> 2.12.0
|    |    |    \--- org.eclipse.emf:org.eclipse.emf.common:(2.8,3.0) -> 2.12.0
|    |    \--- org.eclipse.core:runtime:3.10.0-v20140318-2214
|    |         +--- org.eclipse:osgi:[3.7.0,4.0.0) -> 3.10.0-v20140606-1445
|    |         +--- org.eclipse.equinox:common:[3.6.100,4.0.0) -> 3.6.200-v20130402-1505
|    |         +--- org.eclipse.core:jobs:[3.2.0,4.0.0) -> 3.6.0-v20140424-0053
|    |         |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
|    |         +--- org.eclipse.equinox:registry:[3.4.0,4.0.0) -> 3.5.400-v20140428-1507
|    |         |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
|    |         +--- org.eclipse.equinox:preferences:[3.4.0,4.0.0) -> 3.5.200-v20140224-1527
|    |         |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
|    |         +--- org.eclipse.core:contenttype:[3.3.0,4.0.0) -> 3.4.200-v20140207-1251
|    |         |    +--- org.eclipse.equinox:preferences:[3.2.0,4.0.0) -> 3.5.200-v20140224-1527 (*)
|    |         |    +--- org.eclipse.equinox:registry:[3.2.0,4.0.0) -> 3.5.400-v20140428-1507 (*)
|    |         |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
|    |         \--- org.eclipse.equinox:app:[1.0.0,) -> 1.3.200-v20130910-1609
|    |              +--- org.eclipse.equinox:registry:[3.4.0,4.0.0) -> 3.5.400-v20140428-1507 (*)
|    |              \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
|    +--- org.eclipse.emf:org.eclipse.emf.mwe.core:[1.3.5, 1.3.13] -> 1.3.13
|    |    +--- org.eclipse.emf:org.eclipse.emf.mwe2.runtime:[2.8.3] -> 2.8.3
|    |    |    \--- com.google.inject:guice:3.0 (*)
|    |    +--- commons-cli:commons-cli:1.2
|    |    \--- commons-logging:commons-logging:1.1.3 -> 1.2
|    +--- org.eclipse.emf:org.eclipse.emf.mwe.utils:[1.3.5, 1.3.13] -> 1.3.13
|    |    \--- org.eclipse.emf:org.eclipse.emf.mwe.core:1.3.13 (*)
|    \--- net.sourceforge.streamsupport:streamsupport:[1.4.2, 1.5.2] -> 1.5.4
\--- project :protelis-lang
     +--- com.google.code.findbugs:findbugs:[3.0.0, 3.0.1] -> 3.0.1 (*)
     +--- org.apache.commons:commons-math3:[3.3, 3.6.1] -> 3.6.1
     +--- org.slf4j:slf4j-api:[1.7.0, 1.8[ -> 1.7.25
     \--- project :protelis-interpreter (*)
```

More in depth:
```
gradle -q dependencyInsight --dependency guava
com.google.guava:guava:21.0 (conflict resolution)

com.google.guava:guava:[10.0.1,14.0.1] -> 21.0
+--- org.eclipse.xtext:org.eclipse.xtext:2.8.4
|    +--- org.protelis:protelis.parser:5.0.0
|    |    \--- project :protelis-interpreter
|    |         +--- compile
|    |         \--- project :protelis-lang
|    |              \--- compile
|    \--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.8.4
|         \--- org.protelis:protelis.parser:5.0.0 (*)
+--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.8.4 (*)
+--- org.eclipse.xtext:org.eclipse.xtext.util:2.8.4
|    +--- org.eclipse.xtext:org.eclipse.xtext:2.8.4 (*)
|    \--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.8.4 (*)
\--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.8.4
     \--- org.eclipse.xtext:org.eclipse.xtext:2.8.4 (*)

com.google.guava:guava:[11.0, 19.0-rc2] -> 21.0
\--- org.danilopianini:javalib-java7:0.6.1
     +--- project :protelis-interpreter
     |    +--- compile
     |    \--- project :protelis-lang
     |         \--- compile
     \--- org.danilopianini:javalib:5.0.0
          \--- project :protelis-interpreter (*)

com.google.guava:guava:[11.0, 22[ -> 21.0
\--- project :protelis-interpreter
     +--- compile
     \--- project :protelis-lang
          \--- compile

com.google.guava:guava:[r03, 19.0] -> 21.0
\--- org.danilopianini:javalib:5.0.0
     \--- project :protelis-interpreter
          +--- compile
          \--- project :protelis-lang
               \--- compile
```

So Guava is forced to version 21, and it should get properly incorporated in the release.

Can you add more detail on the issues you are experiencing? Are you using the release JAR? Are you using Maven rather than Gradle?
I can foresee issues with the latest, since the dependency resolution strategy differs between Gradle and Maven, with [the second being arguably more sane](https://danysk.github.io/information%20technology/gradle-dependency-resolution-is-insane/), and I see a valid dependency range that does not include Guava 19.0 where [`newLinkedHashMapWithExpectedSize`](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Maps.html#newLinkedHashMapWithExpectedSize(int)) was introduced.

**Comment by DanySK** [comment]
I believe your latest pull request correctly forces Guava 19.0 as minimum required version. Please close this issue if you no longer experience the problem.

**Comment by jakebeal** [comment]
I am using Maven (required in my circumstances) to obtain release 10.3.1, which turns out to have a rather messy set of conflicting Guava version requirements embedded within its dependencies.  

For now, I have kludged around in my project by forcing an exclusion of Guava in the release, and am awaiting release 10.3.2 to confirm that the new version is working correctly.
