### ISSUE TITLE
Adding a new file causes IllegalArgumentException

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#152]
I have an existing Protelis program that works nicely. I'm loading it into Protelis with `ProtelisLoader.parse` and passing the path to the pt file inside my classpath ('/protelis/foo/bar.pt').
I have some common functions that I want to share with another Protelis program, so I want to create a common module to share between both programs. I started by creating a file named `common.pt` next to my existing program file with the following contents
```
module foo:common

import protelis:coord:sparsechoice
```
I then added `import foo:common` to my current program file.

When I make this change I get an error from the loader.
```
31950 [main] DEBUG Protelis Loader [] {}- /protelis/bar/foo.pt is not a URI that points to a resolvable resource, nor is classpath://protelis/bar/foo.pt.pt

Error, line 2: Couldn't resolve reference to Module 'protelis:coord:meta'.                                  
Error, line 3: Couldn't resolve reference to Module 'protelis:coord:spreading'.
Error, line 27: Couldn't resolve reference to EObject 'distanceTo'.
Error, line 44: Couldn't resolve reference to EObject 'boundSpreading'.
Error, line 45: Couldn't resolve reference to EObject 'closerThan'.
Error, line 207: Couldn't resolve reference to EObject 'boundSpreading'.
Error, line 229: Couldn't resolve reference to EObject 'nbrRangeHop'.
Error, line 241: Couldn't resolve reference to EObject 'distanceToWithMetric'.
Error, line 255: Couldn't resolve reference to EObject 'nbrRangeHop'.                                              
Error, line 266: Couldn't resolve reference to EObject 'boundSpreading'.                                           Error, line 515: Couldn't resolve reference to EObject 'nbrRange'.                                                 
Error, line 529: Couldn't resolve reference to EObject 'broadcastWithMetric'.
Error, line 529: Couldn't resolve reference to EObject 'distanceToWithMetric'.
Error, line 547: Couldn't resolve reference to EObject 'broadcastWithMetric'.
Error, line 578: Couldn't resolve reference to EObject 'broadcast'.
Error, line 7: Couldn't resolve reference to Module 'protelis:coord:spreading'.
Error, line 86: Couldn't resolve reference to EObject 'roundTripTime'.
Error, line 4: Couldn't resolve reference to Module 'protelis:coord:sparsechoice'.
Error, line 5: Couldn't resolve reference to Module 'protelis:coord:spreading'.
Error, line 32: Couldn't resolve reference to EObject 'roundTripTime'.
Error, line 32: Couldn't resolve reference to EObject 'S'.
Error, line 32: Couldn't resolve reference to EObject 'nbrRange'.
Error, line 142: Couldn't resolve reference to EObject 'distanceTo'.
Error, line 160: Couldn't resolve reference to EObject 'gradcast'.
Error, line 1: missing EOF at '/'

        at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:358) ~[protelis-interpreter-10.5.2.jar!/:10.5.2]                                                                                                                        
at org.protelis.lang.ProtelisLoader.parseAnonymousModule(ProtelisLoader.java:220) ~[protelis-interpreter-10.5.2.jar!/:10.5.2]                                                                                                         
at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:200) ~[protelis-interpreter-10.5.2.jar!/:10.5
.2]
...
```

What am I doing wrong?

**Comment by DanySK** [comment]
My guess is that the current parser is unable to understand a module that exists just as collection of pointers to other modules (this, by the way, rises a question about whether it should be the case of thinking about a different / better structured module organization in Protelis). Could you please try to change the module to:

```
module foo:common

import protelis:coord:sparsechoice

1
```

The existence of the main script may trick the parser into thinking this is a valid program.

**Comment by jschewebbn** [comment]
That works!

**Comment by jschewebbn** [comment]
I spoke too soon. I added the dummy file, but forgot to test the import. Once I import the file my test fails. The odd part is that the error is about finding the main file.

**Comment by jschewebbn** [comment]
I want the empty module to contain a set of functions that I use in other Protelis programs. I initially tried adding all of the functions I wanted and got these errors. To keep it simple I started with an empty file that just has imports to see if that is better.
