### ISSUE TITLE
Importing a non-existent module should complain about that, not EOF

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#156]
Right now, when you try to import a non-existent module, ProtelisLoader.parse catches and ignores the IOException, then tries to parse the filename as an anonymous module, which of course fails because filenames are not Protelis programs.

This is because it goes through parse, which is being too clever.  We need to make sure that imports aren't going through the top-level parse function and can actually report that they can't find an import, rather than trying to parse the import URI as code.

**Comment by DanySK** [comment]
I changed the reported exception message, it now immediately the unresolvable resource:
```protelis
import non:existent:protelismodule
1
```
produces
```
java.lang.IllegalStateException: Couldn't get resource associated with anonymous program: class path resource [non/existent/protelismodule.pt] cannot be opened because it does not exist
	at org.protelis.lang.ProtelisLoader.resourceFromString(ProtelisLoader.java:299)
	at org.protelis.lang.ProtelisLoader.parseAnonymousModule(ProtelisLoader.java:222)
	at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:203)
	at org.protelis.test.ProgramTester.runProgram(ProgramTester.java:156)
	at org.protelis.test.TestLanguage.testErrorMessage03(TestLanguage.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.io.FileNotFoundException: class path resource [non/existent/protelismodule.pt] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.protelis.lang.ProtelisLoader.loadResourcesRecursively(ProtelisLoader.java:269)
	at org.protelis.lang.ProtelisLoader.loadStringResources(ProtelisLoader.java:322)
	at org.protelis.lang.ProtelisLoader.resourceFromString(ProtelisLoader.java:297)
	... 30 more
```
Is this enough?

**Comment by jakebeal** [comment]
That looks good as a first pass resolution to me.  Let's try it and see.

**Comment by DanySK** [comment]
OK, let me know, if it's ok I'm going to close this.
