### ISSUE TITLE
java.lang.IncompatibleClassChangeError when Protelis is launched from Eclipse Phonon

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#157]
When executing within Eclipse Phonon, Protelis crashes and complains about `java.lang.IncompatibleClassChangeError`.
The error does not get raised in previous Eclipse versions, nor if the program are launched through Gradle or other plain Java executors. Also IntelliJ Idea seems to be able to run just fine.

The problem needs to get investigated.

```
19:57:22.672 [main] ERROR i.u.a.core.implementations.Engine - The simulation engine crashed.
java.lang.IncompatibleClassChangeError: Class org.protelis.lang.util.Op2$$Lambda$218/115618826 does not implement the requested interface java8.util.function.BinaryOperator
	at org.protelis.lang.util.Op2.run(Op2.java:112)
	at org.protelis.lang.interpreter.impl.BinaryOp.eval(BinaryOp.java:54)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.If.eval(If.java:50)
	at org.protelis.lang.interpreter.impl.All.lambda$eval$0(All.java:48)
	at org.protelis.lang.interpreter.impl.All.access$lambda$0(All.java)
	at org.protelis.lang.interpreter.impl.All$$Lambda$1.accept(Unknown Source)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:185)
	at org.protelis.lang.interpreter.impl.All.eval(All.java:46)
	at org.protelis.lang.interpreter.impl.FunctionCall.eval(FunctionCall.java:87)
	at org.protelis.lang.interpreter.impl.All.lambda$eval$0(All.java:48)
	at org.protelis.lang.interpreter.impl.All.access$lambda$0(All.java)
	at org.protelis.lang.interpreter.impl.All$$Lambda$1.accept(Unknown Source)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:185)
	at org.protelis.lang.interpreter.impl.All.eval(All.java:46)
	at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:81)
	at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:45)
	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.execute(RunProtelisProgram.java:159)
	at it.unibo.alchemist.model.implementations.reactions.AReaction.execute(AReaction.java:283)
	at it.unibo.alchemist.core.implementations.Engine.doStep(Engine.java:166)
	at it.unibo.alchemist.core.implementations.Engine.run(Engine.java:377)
	at it.unibo.alchemist.AlchemistRunner.lambda$4(AlchemistRunner.java:184)
	at it.unibo.alchemist.AlchemistRunner.lambda$9(AlchemistRunner.java:233)
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:186)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:129)
Exception in thread "main" java.lang.IllegalStateException: java.lang.IncompatibleClassChangeError: Class org.protelis.lang.util.Op2$$Lambda$218/115618826 does not implement the requested interface java8.util.function.BinaryOperator
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:193)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:129)
Caused by: java.lang.IncompatibleClassChangeError: Class org.protelis.lang.util.Op2$$Lambda$218/115618826 does not implement the requested interface java8.util.function.BinaryOperator
	at org.protelis.lang.util.Op2.run(Op2.java:112)
	at org.protelis.lang.interpreter.impl.BinaryOp.eval(BinaryOp.java:54)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.If.eval(If.java:50)
	at org.protelis.lang.interpreter.impl.All.lambda$eval$0(All.java:48)
	at org.protelis.lang.interpreter.impl.All.access$lambda$0(All.java)
	at org.protelis.lang.interpreter.impl.All$$Lambda$1.accept(Unknown Source)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:185)
	at org.protelis.lang.interpreter.impl.All.eval(All.java:46)
	at org.protelis.lang.interpreter.impl.FunctionCall.eval(FunctionCall.java:87)
	at org.protelis.lang.interpreter.impl.All.lambda$eval$0(All.java:48)
	at org.protelis.lang.interpreter.impl.All.access$lambda$0(All.java)
	at org.protelis.lang.interpreter.impl.All$$Lambda$1.accept(Unknown Source)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:185)
	at org.protelis.lang.interpreter.impl.All.eval(All.java:46)
	at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:81)
	at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:45)
	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.execute(RunProtelisProgram.java:159)
	at it.unibo.alchemist.model.implementations.reactions.AReaction.execute(AReaction.java:283)
	at it.unibo.alchemist.core.implementations.Engine.doStep(Engine.java:166)
	at it.unibo.alchemist.core.implementations.Engine.run(Engine.java:377)
	at it.unibo.alchemist.AlchemistRunner.lambda$4(AlchemistRunner.java:184)
	at it.unibo.alchemist.AlchemistRunner.lambda$9(AlchemistRunner.java:233)
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:186)
	... 1 more
```

**Comment by DanySK** [comment]
This may to be related to eclipse/xtext#1231. A workaround could be forcing `org.eclipse.platform:org.eclipse.equinox.common:3.10.0` as dependency. This needs further testing and a hotfix.

**Comment by DanySK** [comment]
I investigated this issue, and it is actually much deeper than I first guessed. Looks like bytecode validation has improved, and retrolambda seems unable to trick the bytecode into using streamsupport.
@jakebeal, considering that:
* Java 8 support on modern [Android is considered complete](https://developer.android.com/studio/write/java8-support) (since 
[Android Nougat, back in 2016](https://en.wikipedia.org/wiki/Android_Nougat)
* [Java 7 reached end of life in 2015](https://java.com/en/download/faq/java_7.xml)

I believe we it's time to move Protelis to a standard Java 8 setup -- or are there any other restrictions I cannot remember of?

At this moment, the Gradle build seems to work correctly, but we cannot run tests in Eclipse. Which means that future issues may get very hard to debug. I can probably work this around by writing methods explicitly returning `java8.util.*` classes, but it will make the code less readable.

**Comment by DanySK** [comment]
I can apparently work this around by forcing the compiler to work with a custom interface rather than casting the Protelis operators to a intersection types (streamsupport functions & Serializable).

I am writing a workaround for this.

**Comment by jakebeal** [comment]
@radarku I seem to recall that you needed support for Java 7 for some of your platforms.  Is this still the case?

**Comment by DanySK** [comment]
I am closing this issue as it has been worked around in a reasonably elegant way. But let's still discuss whether there is still something blocking us from upgrading to Java 8.
