### ISSUE TITLE
Eclipse resolution errors are opaque

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#177]
The Eclipse plugin often reports errors saying that it cannot resolve a reference to an EObject, a Module, or a JVM declared type. These errors are opaque and do not give any hint of how to resolve them.

**Comment by DanySK** [comment]
Can you provide some minimal examples? I believe they are related to Xtext's cross referencing.

**Comment by jschewebbn** [comment]
Here's  a stack trace from our CI system using Protelis 12.0.0.

```
12:39:54  com.bbn.protelis.networkresourcemanagement.NS2ParserTest > testSimpleGraph FAILED
12:39:54      java.lang.IllegalArgumentException: The Protelis program cannot be created because of the following errors:
12:39:54      Error, line 3, column 8: Couldn't resolve reference to ProtelisModule 'protelis:coord:meta'.
12:39:54      Error, line 59, column 5: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 74, column 5: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 87, column 5: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 141, column 5: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 166, column 7: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 536, column 5: Couldn't resolve reference to EObject 'multiInstance'.
12:39:54      Error, line 554, column 5: Couldn't resolve reference to EObject 'multiInstance'.
12:39:54      Error, line 704, column 5: Couldn't resolve reference to EObject 'boundSpreading'.
12:39:54      Error, line 2, column 8: Couldn't resolve reference to ProtelisModule 'protelis:coord:accumulation'.
12:39:54      Error, line 32, column 55: Couldn't resolve reference to EObject 'diameter'.
12:39:54      Error, line 159, column 9: Couldn't resolve reference to EObject 'C'.
12:39:54      Error, line 45, column 60: mismatched input 'getRegionIdentifier' expecting ']'
12:39:54      Error, line 45, column 79: extraneous input '(' expecting ')'
12:39:54      Error, line 45, column 83: mismatched input ')' expecting '}'
12:39:54      Error, line 45, column 88: missing EOF at ')'
12:39:54          at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:370)
12:39:54          at org.protelis.lang.ProtelisLoader.parseURI(ProtelisLoader.java:255)
12:39:54          at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:210)
12:39:54          at com.bbn.protelis.networkresourcemanagement.BasicNetworkFactory.createServer(BasicNetworkFactory.java:58)
12:39:54          at com.bbn.protelis.networkresourcemanagement.testbed.Scenario.lambda$new$0(Scenario.java:167)
12:39:54          at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
12:39:54          at com.bbn.protelis.networkresourcemanagement.testbed.Scenario.<init>(Scenario.java:158)
12:39:54          at 
```

The file being loaded is
```
module com:bbn:resourcemanagement:resourcetracker

import com.bbn.protelis.networkresourcemanagement.ResourceReport.getShortEstimationWindow

import protelis:coord:accumulation
import protelis:coord:spreading
import protelis:coord:meta
import protelis:lang:utils
import protelis:coord:nonselfstabilizing:accumulation

// Deprecated --> will be replaced in a future Protelis release
def once(v) {
    rep(x <- v) { x };
}

public def countDevices(potential) {
    C(potential, sum, 1, 0)
}

// TODO: check if I can just do this as Tuple.union
public def union(a, b) {
    a.union(b);
}

public def C(potential, reduce, local, null) {
    let nonce = once(self.nextRandomDouble());
    rep (v <- local) {
        reduce.apply(local,
            /*
             * TODO: switch to accumulateHood
             */
            hood(
                (a, b) -> { reduce.apply(a, b) },
                // expression that will be evaluated if the field is empty
                null,
                mux (nbr(getParent(potential, (v) -> { nonce })) == nonce) {
                    nbr(v)
                } else { null }
            )
        )
    }
}

public def regionSet(potential) {
        C(potential, union, unionHood(nbr([self.getDevice()getRegionIdentifier()])), []);
}

def countNodes() {
    let nonce = once(self.nextRandomDouble());
    let leader = nonce == gossip(nonce, min);
        self.getExecutionEnvironment().put("blue",leader);
    let d = hopDistanceTo(leader);
    countDevices(d);
}

def nbrRegions() {
    let nonce = once(self.nextRandomDouble());
    let leader = nonce == gossip(nonce, min);
    //self.putEnvironmentVariable("blue",leader);
    let d = hopDistanceTo(leader);
    [leader, countDevices(d), regionSet(d)];
}

//countNodes();
//minHood(nbr(self.getDeviceUID()))
//nbrRegions();



let rgn = self.getDevice().getRegionIdentifier();
let s = multiRegion(rgn,(n) -> { rgn == n },countNodes,[]);
//multiRegion(rgn,(n) -> { rgn == n },nbrRegions,[]);
//multiRegion(rgn,(n) -> { rgn == n },() -> { [rgn, self.getDeviceUID()] },[]);

let report = self.getDevice().getResourceReport(getShortEstimationWindow()); 
let d = report.getComputeLoad();
let c = report.getNodeComputeCapacity();

[d,c,s];
```

**Comment by jschewebbn** [comment]
This may not be in the right bug though. This isn't output from Eclipse, but rather from the loader. Please tell me which ticket this belongs in.

A previous version of the test is at https://github.com/map-dcomp/P2Protelis/blob/master/src/test/java/com/bbn/protelis/networkresourcemanagement/NS2ParserTest.java
I believe I have only changed the name of the protelis file since this was published.

**Comment by jschewebbn** [comment]
In this file I'm getting errors from Eclipse about being unable to resolve references to:
  * getParent - line 36
  * hopDistanceTo - line 52, 60
  * multiRegion - line 71

According to about eclipse I have version 6.0.0 of the protelis.parser and  protelis.parser.ui plugins installed. Perhaps I have an old version? I've tried checking for an update, but #228 is preventing that.


```
module com:bbn:resourcemanagement:resourcetracker

import com.bbn.protelis.networkresourcemanagement.ResourceReport.getShortEstimationWindow

import protelis:coord:accumulation
import protelis:coord:spreading
import protelis:coord:meta
import protelis:lang:utils
import protelis:coord:nonselfstabilizing:accumulation

// Deprecated --> will be replaced in a future Protelis release
def once(v) {
    rep(x <- v) { x }
}

public def countDevices(potential) {
    C(potential, sum, 1, 0)
}

// TODO: check if I can just do this as Tuple.union
public def union(a, b) {
    a.union(b)
}

public def C(potential, reduce, local, null) {
    let nonce = once(self.nextRandomDouble());
    rep (v <- local) {
        reduce.apply(local,
            /*
             * TODO: switch to accumulateHood
             */
            hood(
                (a, b) -> { reduce.apply(a, b) },
                // expression that will be evaluated if the field is empty
                null,
                mux (nbr(getParent(potential, (v) -> { nonce })) == nonce) {
                    nbr(v)
                } else { null }
            )
        )
    }
}

public def regionSet(potential) {
    C(potential, union, unionHood(nbr([self.getDevice().getRegionIdentifier()])), [])
}

def countNodes() {
    let nonce = once(self.nextRandomDouble());
    let leader = nonce == gossip(nonce, min);
    self.getExecutionEnvironment().put("blue",leader);
    let d = hopDistanceTo(leader);
    countDevices(d)
}

def nbrRegions() {
    let nonce = once(self.nextRandomDouble());
    let leader = nonce == gossip(nonce, min);
    //self.putEnvironmentVariable("blue",leader);
    let d = hopDistanceTo(leader);
    [leader, countDevices(d), regionSet(d)]
}

//countNodes();
//minHood(nbr(self.getDeviceUID()))
//nbrRegions();



let rgn = self.getDevice().getRegionIdentifier();
let s = multiRegion(rgn,(n) -> { rgn == n },countNodes,[]);
//multiRegion(rgn,(n) -> { rgn == n },nbrRegions,[]);
//multiRegion(rgn,(n) -> { rgn == n },() -> { [rgn, self.getDeviceUID()] },[]);

let report = self.getDevice().getResourceReport(getShortEstimationWindow()); 
let d = report.getComputeLoad();
let c = report.getNodeComputeCapacity();

[d,c,s]
```

**Comment by DanySK** [comment]
Hi @jschewebbn, do errors persist if you upgrade from the Eclipse Marketplace?

**Comment by jschewebbn** [comment]
I do not see these errors with the upgrade. You can close this.
