### ISSUE TITLE
Update alchemist tutorial to latest Protelis

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#236]
The Protelis-Alchemist-tutorial is not using the latest Protelis. It needs to be updated.

**Comment by jakebeal** [comment]
In fact, it's currently broken and cannot run:

````
Exception in thread "main" java.lang.VerifyError: class it.unibo.alchemist.model.implementations.environments.AbstractLinkingRuleEnvironment overrides final method updateNeighborhood.(Lit/unibo/alchemist/model/interfaces/Node;)V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at it.unibo.alchemist.loader.YamlLoader.<clinit>(YamlLoader.java:144)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:107)
:runAlchemist FAILED
:runAlchemist (Thread[main,5,main]) completed. Took 1.485 secs.
````

**Comment by jakebeal** [comment]
This is currently blocking @erinmori26

**Comment by DanySK** [comment]
I'm tackling this. The tutorial is updated and under CI. The problem is that we currently have the same repository listed twice, once in the @AlchemistSimulator organization and once in the @Protelis organization.
I propose the following:
1. Decide where to keep the tutorial -- I'd be in favor of hosting it on the Alchemist organization, since Alchemist includes Protelis as a library and it is required for the tutorial, I'd like to keep Protelis as clean as possible
2. Produce a wiki-style website for the demo, completely integrated into the repository, via [Orchid](https://orchid.netlify.com/). This way, we prevent code and documentation to fall askew
3. Link such website on the Protelis and Alchemist websites

@jakebeal, do you agree?

**Comment by jakebeal** [comment]
I don't care which organization, as long as it's clearly linked in both the websites and the README files.
