### ISSUE TITLE
Tuple.map: This program has attempted to build a field twice with the same code path.

### ISSUE THREAD

**Issue by fedpet** [Protelis/Protelis#254]
As discussed with @DanySK  it should be possible to access a field inside a Tuple.map, but currently it results in an exception.

Code:
```
let f = nbr(1);
[1,2,3,4].map { t -> f; t }
```

Exception:
```
java.lang.IllegalStateException: This program has attempted to build a field twice with the same code path. This is probably a bug in Protelis. Debug information: tried to insert CodePath[-1, -2147483645, 0, 1, -2147483625, -2147483623, -2147483620, 23162479, 1853451631, 1970482541, 1868854636, 1698309218, 975449649, 975465825, 1882274340, 1768846959, 1801793594, 610365039, 28208, -2147483645, 0, -2147483595, -2147483620, 23162479, 1853451631, 1970482541, 1868854636, 1698309218, 975449649, 975465825, 1882274340, 1768846959, 1801793594, 610365039, 28208, -2147483645, 0, -2147483595] into {CodePath[-1, -2147483645, 0, -2147483626, 0, -2147483605]=1.0, CodePath[-1, -2147483645, 0, 1, -2147483625, -2147483623, -2147483620, 23162479, 1853451631, 1970482541, 1868854636, 1698309218, 975449649, 975465825, 1882274340, 1768846959, 1801793594, 610365039, 28208, -2147483645, 0, -2147483595]=0, CodePath[-1, -2147483645, 0, 1, -2147483625, -2147483623, -2147483620, 23162479, 1853451631, 1970482541, 1868854636, 1698309218, 975449649, 975465825, 1882274340, 1768846959, 1801793594, 610365039, 28208, -2147483645, 0, -2147483595, -2147483620, 23162479, 1853451631, 1970482541, 1868854636, 1698309218, 975449649, 975465825, 1882274340, 1768846959, 1801793594, 610365039, 28208, -2147483645, 0, -2147483595]=0}. Value to insert: 0, existing one: 0
	at org.protelis.vm.impl.AbstractExecutionContext.buildField(AbstractExecutionContext.java:130)
	at org.protelis.vm.impl.AbstractExecutionContext.buildField(AbstractExecutionContext.java:109)
	at org.protelis.lang.interpreter.impl.Variable.evaluate(Variable.java:61)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	... 40 more
```

**Comment by DanySK** [comment]
This is actually expected, as java methods in general do not understand alignment, and when trying to restrict the field on the second element the same code path is generated twice.
Now, I could actually provide specific support for tuple methods. I'm not sure if it's worth the effort, though, especially if we plan to tackle #182 and revisit Protelis collections.
In many cases, this issue could be tackled by using mapHood (or setHood) as proposed in #91.

I would go for the second approach, and create the builtin `foldToMap`, which translates the field to a map including self.
