### ISSUE TITLE
Switching to expression function syntax breaks at runtime

### ISSUE THREAD

**Issue by metaphori** [Protelis/Protelis#262]
That is, by changing from

```
def densityEstimation(p, range, w) {
	countNearby(range) / (p * PI * range ^ 2 * w)
}
```
to
```
def densityEstimation(p, range, w) =
	countNearby(range) / (p * PI * range ^ 2 * w)
```
yields the following:

```
10:27:38.887 [main] ERROR i.u.a.core.implementations.Engine - The simulation engine crashed.
org.protelis.lang.interpreter.util.ProtelisRuntimeException: The cause exception did not provide any useful message.
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:129)
	at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:95)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.lambda$projectAndEval$2(AbstractAnnotatedTree.java:248)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.projectAndEval(AbstractAnnotatedTree.java:247)
	at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:45)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.All.lambda$evaluate$0(All.java:52)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.All.evaluate(All.java:50)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:94)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:95)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.lambda$projectAndEval$2(AbstractAnnotatedTree.java:248)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.projectAndEval(AbstractAnnotatedTree.java:247)
	at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:45)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.All.lambda$evaluate$0(All.java:52)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.All.evaluate(All.java:50)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:65)
	at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:44)
	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.execute(RunProtelisProgram.java:160)
	at it.unibo.alchemist.model.implementations.reactions.AbstractReaction.execute(AbstractReaction.java:130)
	at it.unibo.alchemist.core.implementations.Engine.doStep(Engine.java:188)
	at it.unibo.alchemist.core.implementations.Engine.run(Engine.java:399)
	at it.unibo.alchemist.AlchemistRunner.lambda$launch$0(AlchemistRunner.java:179)
	at it.unibo.alchemist.AlchemistRunner.lambda$prepareSimulations$11(AlchemistRunner.java:320)
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:181)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:143)
Caused by: java.lang.NullPointerException: null
	at org.protelis.lang.ProtelisLoader$Dispatch.block(ProtelisLoader.java:436)
	at org.protelis.lang.ProtelisLoader$Dispatch.lambda$null$5(ProtelisLoader.java:681)
	at org.protelis.lang.datatype.FunctionDefinition.initBody(FunctionDefinition.java:159)
	at org.protelis.lang.datatype.FunctionDefinition.getBody(FunctionDefinition.java:127)
	at org.protelis.lang.interpreter.impl.FunctionCall.getBody(FunctionCall.java:103)
	at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:89)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	... 36 common frames omitted
Exception in thread "main" java.lang.IllegalStateException: org.protelis.lang.interpreter.util.ProtelisRuntimeException: null
	at monitoringTraces:densityEstimation at line number 33
	at monitoringTraces:crowdTracking at line number 33
Fully detailed interpreter trace:
org.protelis.lang.interpreter.util.ProtelisRuntimeException: null
	at: monitoringTraces:densityEstimation(0.005, 30.0, 0.25){ null } at line number 33
	at: monitoringTraces:densityEstimation/3.apply(p, range, w) at line number 33
	at: let densityEst = apply at line number 33
	at: monitoringTraces:crowdTracking(0.005, 30.0, 0.25, 1.08, 2.17, 300.0, 60.0){ let; ...; if } at line number 89
	at: monitoringTraces:crowdTracking/7.apply(p, crowdRange, w, crowdedDensity, dangerousThreshold, groupSize, timeFrame) at line number 89
	at: let crowding = apply at line number 89
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:188)
	at it.unibo.alchemist.Alchemist.main(Alchemist.java:143)
Caused by: org.protelis.lang.interpreter.util.ProtelisRuntimeException: null
	at monitoringTraces:densityEstimation at line number 33
	at monitoringTraces:crowdTracking at line number 33
Fully detailed interpreter trace:
org.protelis.lang.interpreter.util.ProtelisRuntimeException: null
	at: monitoringTraces:densityEstimation(0.005, 30.0, 0.25){ null } at line number 33
	at: monitoringTraces:densityEstimation/3.apply(p, range, w) at line number 33
	at: let densityEst = apply at line number 33
	at: monitoringTraces:crowdTracking(0.005, 30.0, 0.25, 1.08, 2.17, 300.0, 60.0){ let; ...; if } at line number 89
	at: monitoringTraces:crowdTracking/7.apply(p, crowdRange, w, crowdedDensity, dangerousThreshold, groupSize, timeFrame) at line number 89
	at: let crowding = apply at line number 89
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:129)
	at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:95)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.lambda$projectAndEval$2(AbstractAnnotatedTree.java:248)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.projectAndEval(AbstractAnnotatedTree.java:247)
	at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:45)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.All.lambda$evaluate$0(All.java:52)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.All.evaluate(All.java:50)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:94)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:95)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:293)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.lambda$projectAndEval$2(AbstractAnnotatedTree.java:248)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.projectAndEval(AbstractAnnotatedTree.java:247)
	at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:45)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.lang.interpreter.impl.All.lambda$evaluate$0(All.java:52)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:168)
	at org.protelis.lang.interpreter.impl.All.evaluate(All.java:50)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:65)
	at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:44)
	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.execute(RunProtelisProgram.java:160)
	at it.unibo.alchemist.model.implementations.reactions.AbstractReaction.execute(AbstractReaction.java:130)
	at it.unibo.alchemist.core.implementations.Engine.doStep(Engine.java:188)
	at it.unibo.alchemist.core.implementations.Engine.run(Engine.java:399)
	at it.unibo.alchemist.AlchemistRunner.lambda$launch$0(AlchemistRunner.java:179)
	at it.unibo.alchemist.AlchemistRunner.lambda$prepareSimulations$11(AlchemistRunner.java:320)
	at it.unibo.alchemist.AlchemistRunner.launch(AlchemistRunner.java:181)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.protelis.lang.ProtelisLoader$Dispatch.block(ProtelisLoader.java:436)
	at org.protelis.lang.ProtelisLoader$Dispatch.lambda$null$5(ProtelisLoader.java:681)
	at org.protelis.lang.datatype.FunctionDefinition.initBody(FunctionDefinition.java:159)
	at org.protelis.lang.datatype.FunctionDefinition.getBody(FunctionDefinition.java:127)
	at org.protelis.lang.interpreter.impl.FunctionCall.getBody(FunctionCall.java:103)
	at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:89)
	at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.eval(AbstractAnnotatedTree.java:123)
	... 36 more

```

**Comment by DanySK** [comment]
Bug confirmed and reproduced:
```groovy
// EXPECTED_RESULT: 15.2
def f(x, y) = x + y
f(12.2, 3)
```
