### ISSUE TITLE
Protelis appears to require some plugin properties

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#282]
Using Protelis 13.1.0 my unit tests pass, but when I run the application in production I get the following error. It seems that a dependent jar is missing from Protelis.

```
2019-10-22 16:54:35,205 [main] ERROR com.bbn.map.utils.LogExceptionHandler [] {}- Unhandled exception: The string resource '_UI_DiagnosticRoot_diagnostic' could not be located
java.util.MissingResourceException: The string resource '_UI_DiagnosticRoot_diagnostic' could not be located
        at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:480) ~[map-agent.jar:?]
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:385) ~[map-agent.jar:?]
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:499) ~[map-agent.jar:?]
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:491) ~[map-agent.jar:?]
        at org.eclipse.emf.ecore.util.Diagnostician.createDefaultDiagnostic(Diagnostician.java:88) ~[map-agent.jar:?]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:107) ~[map-agent.jar:?]
        at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:268) ~[map-agent.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:316) ~[map-agent.jar:?]
        at com.bbn.map.ap.MapNetworkFactory.createServer(MapNetworkFactory.java:113) ~[map-agent.jar:?]
        at com.bbn.map.hifi.HiFiAgent.<init>(HiFiAgent.java:591) ~[map-agent.jar:?]
        at com.bbn.map.hifi.HiFiAgent.main(HiFiAgent.java:472) ~[map-agent.jar:?]
```

**Comment by jschewebbn** [comment]
I did find a workaround of adding a file 'plugin.properties' to my resources with the below text in it prevents the error. However I would have expected that this would be picked up from the dependencies.

```
_UI_DiagnosticRoot_diagnostic=_UI_DiagnosticRoot_diagnostic
```

**Comment by jakebeal** [comment]
@DanySK We've got more people running into this at BBN as well now --- it looks like it's going to hit anyone running from a JAR file. Can you let us know if you've been able to diagnose the issue?

**Comment by jschewebbn** [comment]
I created a minimal example to test with
```
git clone https://github.com/jschewebbn/protelis-debug.git
cd protelis-debug
./gradlew shadowJar
java -jar build/libs/debug-protelis.jar 
```

**Comment by DanySK** [comment]
[This](https://www.eclipse.org/forums/index.php/t/487563/) seems to be the root of the issue:

> emf.common needs a plugin.properties file which contains a following entry: `_UI_DiagnosticRoot_diagnostic=_UI_DiagnosticRoot_diagnostic`

I guess such file is provided by the libraries, but not included in the fatJar / shadow jar. I investigated the filters and found no obvious candidates for the file removal. My hypothesis is that there is a conflict over such file between libraries, in this case it would be pretty annoying to fix.

I need some further investigation
