### ISSUE TITLE
Problem with using Java function as argument to C

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#385]
At this point I do not have a self-contained example. However based on some email conversations with @DanySK this should provide enough information on where to look for the issue.

The protelis code below where `sumTotalDemand` is a Java function. Generates the following exception. Replacing `sumTotalDemand` with `{ sumTotalDemand() }` works around this issue.
```
   self.getDevice().getAllServices()
    .map { service ->
        let leader = self.getDevice().isTotalDemandLeaderForService(service)
        let cResult = C(hopDistanceTo(leader),
                     sumTotalDemand,
                     self.getDevice().getLocalTotalDemandForService(service),
                     nullTotalDemand())
        [leader, service, cResult]
    }
    .filter { it.get(0) }
    .map { self.getDevice().setTotalDemandForService(it.get(1), it.get(2))
```

```
11:43:15      org.protelis.lang.interpreter.util.ProtelisRuntimeException: Invocation of public org.protelis.lang.datatype.Tuple org.protelis.lang.datatype.impl.ArrayTupleImpl.map(org.protelis.vm.ExecutionContext,org.protelis.lang.datatype.FunctionDefinition) on ['AppCoordinates {test, test-service, 1}'] with arguments (com.bbn.protelis.networkresourcemanagement.ExecutionContext@685559c5: ExecutionContext,protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0/1: FunctionDefinition) failed because of an internal ProtelisRuntimeException; please look at the stacktrace for further information
11:43:15      org.protelis.lang.interpreter.util.ProtelisRuntimeException: Invocation of public org.protelis.lang.datatype.Tuple org.protelis.lang.datatype.impl.ArrayTupleImpl.map(org.protelis.vm.ExecutionContext,org.protelis.lang.datatype.FunctionDefinition) on ['AppCoordinates {test, test-service, 1}'] with arguments (com.bbn.protelis.networkresourcemanagement.ExecutionContext@685559c5: ExecutionContext,protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0/1: FunctionDefinition) failed because of an internal ProtelisRuntimeException; please look at the stacktrace for further information
11:43:15              at protelis:com:bbn:map:resourcetracker:computeTotalDemand between lines 255 and 263
11:43:15      Fully detailed interpreter trace:
11:43:15      org.protelis.lang.interpreter.util.ProtelisRuntimeException: Invocation of public org.protelis.lang.datatype.Tuple org.protelis.lang.datatype.impl.ArrayTupleImpl.map(org.protelis.vm.ExecutionContext,org.protelis.lang.datatype.FunctionDefinition) on ['AppCoordinates {test, test-service, 1}'] with arguments (com.bbn.protelis.networkresourcemanagement.ExecutionContext@685559c5: ExecutionContext,protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0/1: FunctionDefinition) failed because of an internal ProtelisRuntimeException; please look at the stacktrace for further information
11:43:15           at: getAllServices.map(protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0/1) between lines 255 and 263
11:43:15             at: map.filter(protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$filter1:$()0:$l0/0) between lines 255 and 264
11:43:15        at: filter.map(protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$map1:$()0:$l0/0) between lines 255 and 265
11:43:15          at: protelis:com:bbn:map:resourcetracker:computeTotalDemand() at line number 311
11:43:15       at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:102) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:81) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:81) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:82) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.lang.interpreter.impl.All.evaluate(All.java:42) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:66) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:44) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at com.bbn.protelis.networkresourcemanagement.NetworkServer.run(NetworkServer.java:360) ~[P2Protelis-9.4.9.jar:?]
11:43:15           at com.bbn.protelis.networkresourcemanagement.NetworkServer.lambda$startExecuting$1(NetworkServer.java:419) ~[P2Protelis-9.4.9.jar:?]
11:43:15             at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
11:43:15      Caused by: java.lang.UnsupportedOperationException: Invocation of public org.protelis.lang.datatype.Tuple org.protelis.lang.datatype.impl.ArrayTupleImpl.map(org.protelis.vm.ExecutionContext,org.protelis.lang.datatype.FunctionDefinition) on ['AppCoordinates {test, test-service, 1}'] with arguments (com.bbn.protelis.networkresourcemanagement.ExecutionContext@685559c5: ExecutionContext,protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0/1: FunctionDefinition) failed because of an internal ProtelisRuntimeException; please look at the stacktrace for further information
11:43:15              at org.protelis.lang.interpreter.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:276) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:224) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:181) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:106) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         ... 19 more
11:43:15      Caused by: java.lang.reflect.InvocationTargetException
11:43:15             at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
11:43:15        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
11:43:15        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
11:43:15             at org.protelis.lang.interpreter.util.ReflectionUtils.invokePossiblyVoidMethod(ReflectionUtils.java:285) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.lang.interpreter.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:254) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:224) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:181) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:106) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          ... 19 more
11:43:15      Caused by: org.protelis.lang.interpreter.util.ProtelisRuntimeException: org.protelis.lang.datatype.JVMEntity cannot be cast to org.protelis.lang.datatype.FunctionDefinition
11:43:15      org.protelis.lang.interpreter.util.ProtelisRuntimeException: org.protelis.lang.datatype.JVMEntity cannot be cast to org.protelis.lang.datatype.FunctionDefinition
11:43:15         at ⍖:C between lines 67 and 74
11:43:15          at protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0 between lines 258 and 261
11:43:15      Fully detailed interpreter trace:
11:43:15      org.protelis.lang.interpreter.util.ProtelisRuntimeException: org.protelis.lang.datatype.JVMEntity cannot be cast to org.protelis.lang.datatype.FunctionDefinition
11:43:15       at: hood() between lines 67 and 74
11:43:15            at: reduce.apply(local, hood) between lines 63 and 75
11:43:15        at: share (v <- local) { apply } between lines 62 and 76
11:43:15           at: ⍖:C(⍏:hopDistanceTo, sumTotalDemand, getLocalTotalDemandForService, apply) between lines 258 and 261
11:43:15        at: let cResult = ⍖:C between lines 258 and 261
11:43:15              at: protelis:com:bbn:map:resourcetracker:computeTotalDemand:$.:$.0:$.0:$map1:$()0:$l0(AppCoordinates {test, test-service, 1}) at line number -1
11:43:15          at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:102) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:99) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.ShareCall.evaluate(ShareCall.java:129) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:82) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:40) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.All.evaluate(All.java:42) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:82) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.datatype.impl.ArrayTupleImpl.lambda$map$2(ArrayTupleImpl.java:274) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
11:43:15          at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_265]
11:43:15        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
11:43:15        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
11:43:15         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_265]
11:43:15         at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_265]
11:43:15              at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_265]
11:43:15             at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:511) ~[?:1.8.0_265]
11:43:15            at org.protelis.lang.datatype.impl.ArrayTupleImpl.map(ArrayTupleImpl.java:276) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
11:43:15           at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
11:43:15           at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
11:43:15        at org.protelis.lang.interpreter.util.ReflectionUtils.invokePossiblyVoidMethod(ReflectionUtils.java:285) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:254) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:224) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:181) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:106) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             ... 19 more
11:43:15      Caused by: java.lang.ClassCastException: org.protelis.lang.datatype.JVMEntity cannot be cast to org.protelis.lang.datatype.FunctionDefinition
11:43:15              at org.protelis.lang.interpreter.impl.GenericHoodCall.makeCall(GenericHoodCall.java:132) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.impl.GenericHoodCall.lambda$evaluate$1(GenericHoodCall.java:111) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[?:1.8.0_265]
11:43:15           at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
11:43:15       at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_265]
11:43:15           at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_265]
11:43:15          at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_265]
11:43:15            at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
11:43:15            at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
11:43:15             at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
11:43:15        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
11:43:15        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:546) ~[?:1.8.0_265]
11:43:15        at org.protelis.lang.datatype.Field.reduce(Field.java:284) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.datatype.Field.reduceValues(Field.java:311) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.GenericHoodCall.evaluate(GenericHoodCall.java:115) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:99) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.ShareCall.evaluate(ShareCall.java:129) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:82) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15        at org.protelis.lang.interpreter.impl.AssignmentOp.evaluate(AssignmentOp.java:40) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            at org.protelis.lang.interpreter.impl.All.evaluate(All.java:42) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.impl.FunctionCall.evaluate(FunctionCall.java:82) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15           at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15              at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.datatype.impl.ArrayTupleImpl.lambda$map$2(ArrayTupleImpl.java:274) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
11:43:15         at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_265]
11:43:15       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
11:43:15       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
11:43:15        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_265]
11:43:15        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_265]
11:43:15             at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_265]
11:43:15            at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:511) ~[?:1.8.0_265]
11:43:15           at org.protelis.lang.datatype.impl.ArrayTupleImpl.map(ArrayTupleImpl.java:276) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
11:43:15          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
11:43:15          at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
11:43:15       at org.protelis.lang.interpreter.util.ReflectionUtils.invokePossiblyVoidMethod(ReflectionUtils.java:285) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.lang.interpreter.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:254) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15       at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:224) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15          at org.protelis.lang.interpreter.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:181) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.Invoke.evaluate(Invoke.java:106) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15         at org.protelis.vm.impl.AbstractExecutionContext.runInNewStackFrame(AbstractExecutionContext.java:350) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15             at org.protelis.lang.interpreter.impl.AbstractProtelisAST.eval(AbstractProtelisAST.java:91) ~[protelis-interpreter-14.0.0.jar:?]
11:43:15            ... 19 more
```

**Comment by DanySK** [comment]
I think I have an idea of what the root of the issue is -- or, actually, was, if my understanding is correct. Can you try with the latest version and see if it works or if the exception is somewhat different?
